/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mofukasir;

import javax.swing.JFrame;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

public class DashboardAdmin extends javax.swing.JFrame {
private Connection mysqlconfig;
    /**
     * Creates new form DashboardUser
     */
    
    
    public DashboardAdmin() {
        initComponents();
        setTitle("Data Barang");
        setLocationRelativeTo(null);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        try {
            mysqlconfig = Config.configDB();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
        loadData();   


    }
    private void kosong(){
          inputNamaBarang.setText(null);
          inputHargaBarang.setText(null);
          inputStokBarang.setText(null);
          inputTanggalMasuk.setText(null);
          inputKadaluarsa.setText(null);
    }
    
    private void loadData(){
        DefaultTableModel tableModel = new DefaultTableModel();
        tableModel.addColumn("KODE");
        tableModel.addColumn("NAMA");
        tableModel.addColumn("HARGA");
        tableModel.addColumn("STOK");
        tableModel.addColumn("Tanggal Masuk");
        tableModel.addColumn("Tanggal Kadaluarsa");
        try {
            String sql = "SELECT * FROM barang";
            PreparedStatement pstmt = mysqlconfig.prepareStatement(sql);
            ResultSet results = pstmt.executeQuery();
            
            while (results.next()) {
                tableModel.addRow( new String[] {
                    results.getString("kode_barang"),
                    results.getString("nama_barang"),
                    results.getString("harga"),
                    results.getString("stok"),
                    results.getString("tanggal_masuk"),
                    results.getString("tanggal_kadaluarsa"),
                });
            }
            tabelBarang.setModel(tableModel);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error : " + e.getMessage());
        }
    }
     private void cariBarang(String keyword) {
        DefaultTableModel tableModel = new DefaultTableModel();
        tableModel.addColumn("KODE");
        tableModel.addColumn("NAMA");
        tableModel.addColumn("HARGA");
        tableModel.addColumn("STOK");
        tableModel.addColumn("Tanggal Masuk");
        tableModel.addColumn("Tanggal Kadaluarsa");

        try {
            String sql = "SELECT * FROM barang WHERE nama_barang LIKE ?";
            PreparedStatement pstmt = mysqlconfig.prepareStatement(sql);
            pstmt.setString(1, "%" + keyword + "%");
            ResultSet results = pstmt.executeQuery();

            while (results.next()) {
                tableModel.addRow(new String[] {
                    results.getString("kode_barang"),
                    results.getString("nama_barang"),
                    results.getString("harga"),
                    results.getString("stok"),
                    results.getString("tanggal_masuk"),
                    results.getString("tanggal_kadaluarsa"),
                });
            }

            if (tableModel.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "Data barang tidak ditemukan.", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            }

            tabelBarang.setModel(tableModel);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error : " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTransaksi = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        btnNavDataBarang = new javax.swing.JButton();
        btnNavDataPegawai = new javax.swing.JButton();
        btnNavDataTransaksi = new javax.swing.JButton();
        btnNavSupplier = new javax.swing.JButton();
        btnNavTransaksi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelBarang = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        inputHargaBarang = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        inputNamaBarang = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        inputTanggalMasuk = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        inputStokBarang = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        inputKadaluarsa = new javax.swing.JTextField();
        inputCari = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnCari = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        BtnDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setSize(new java.awt.Dimension(1366, 768));

        btnTransaksi.setBackground(new java.awt.Color(153, 153, 153));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Mofuu Store");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnNavDataBarang.setBackground(new java.awt.Color(58, 179, 151));
        btnNavDataBarang.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        btnNavDataBarang.setForeground(new java.awt.Color(255, 255, 255));
        btnNavDataBarang.setText("Data Barang");
        btnNavDataBarang.setBorder(null);
        btnNavDataBarang.setBorderPainted(false);
        btnNavDataBarang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNavDataBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNavDataBarangActionPerformed(evt);
            }
        });

        btnNavDataPegawai.setBackground(new java.awt.Color(0, 204, 204));
        btnNavDataPegawai.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        btnNavDataPegawai.setForeground(new java.awt.Color(255, 255, 255));
        btnNavDataPegawai.setText("Data Pegawai");
        btnNavDataPegawai.setBorder(null);
        btnNavDataPegawai.setBorderPainted(false);
        btnNavDataPegawai.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNavDataPegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNavDataPegawaiActionPerformed(evt);
            }
        });

        btnNavDataTransaksi.setBackground(new java.awt.Color(0, 204, 204));
        btnNavDataTransaksi.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        btnNavDataTransaksi.setForeground(new java.awt.Color(255, 255, 255));
        btnNavDataTransaksi.setText("Data Transaksi");
        btnNavDataTransaksi.setBorder(null);
        btnNavDataTransaksi.setBorderPainted(false);
        btnNavDataTransaksi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNavDataTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNavDataTransaksiActionPerformed(evt);
            }
        });

        btnNavSupplier.setBackground(new java.awt.Color(0, 204, 204));
        btnNavSupplier.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        btnNavSupplier.setForeground(new java.awt.Color(255, 255, 255));
        btnNavSupplier.setText("Data Supplier");
        btnNavSupplier.setBorder(null);
        btnNavSupplier.setBorderPainted(false);
        btnNavSupplier.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNavSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNavSupplierActionPerformed(evt);
            }
        });

        btnNavTransaksi.setBackground(new java.awt.Color(0, 204, 204));
        btnNavTransaksi.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        btnNavTransaksi.setForeground(new java.awt.Color(255, 255, 255));
        btnNavTransaksi.setText("Transaksi");
        btnNavTransaksi.setBorder(null);
        btnNavTransaksi.setBorderPainted(false);
        btnNavTransaksi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNavTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNavTransaksiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout btnTransaksiLayout = new javax.swing.GroupLayout(btnTransaksi);
        btnTransaksi.setLayout(btnTransaksiLayout);
        btnTransaksiLayout.setHorizontalGroup(
            btnTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(btnTransaksiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNavDataBarang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNavDataPegawai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNavDataTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNavSupplier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNavTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        btnTransaksiLayout.setVerticalGroup(
            btnTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnTransaksiLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnNavDataBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnNavDataPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnNavDataTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnNavSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnNavTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabelBarang.setBackground(new java.awt.Color(204, 204, 204));
        tabelBarang.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        tabelBarang.setForeground(new java.awt.Color(51, 51, 51));
        tabelBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelBarang.setRowHeight(30);
        tabelBarang.setRowMargin(5);
        tabelBarang.setSelectionBackground(new java.awt.Color(0, 255, 255));
        tabelBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelBarangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelBarang);

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(58, 179, 151));
        jLabel1.setText("Harga Barang");

        btnLogout.setBackground(new java.awt.Color(58, 179, 151));
        btnLogout.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("Logout");
        btnLogout.setBorder(null);
        btnLogout.setBorderPainted(false);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(58, 179, 151));
        jLabel2.setText("Data Barang - Admin");

        inputHargaBarang.setBackground(new java.awt.Color(255, 255, 255));
        inputHargaBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputHargaBarangActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(58, 179, 151));
        jLabel3.setText("Nama Barang");

        inputNamaBarang.setBackground(new java.awt.Color(255, 255, 255));
        inputNamaBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNamaBarangActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(58, 179, 151));
        jLabel4.setText("Tanggal Masuk");

        inputTanggalMasuk.setBackground(new java.awt.Color(255, 255, 255));
        inputTanggalMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputTanggalMasukActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(58, 179, 151));
        jLabel5.setText("Stok");

        inputStokBarang.setBackground(new java.awt.Color(255, 255, 255));
        inputStokBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputStokBarangActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(58, 179, 151));
        jLabel6.setText("Kadaluarsa");

        inputKadaluarsa.setBackground(new java.awt.Color(255, 255, 255));
        inputKadaluarsa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputKadaluarsaActionPerformed(evt);
            }
        });

        inputCari.setBackground(new java.awt.Color(255, 255, 255));
        inputCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputCariActionPerformed(evt);
            }
        });

        btnAdd.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(58, 179, 151));
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnClear.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        btnClear.setForeground(new java.awt.Color(58, 179, 151));
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnEdit.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(58, 179, 151));
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnCari.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        btnCari.setForeground(new java.awt.Color(58, 179, 151));
        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        btnRefresh.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        btnRefresh.setForeground(new java.awt.Color(58, 179, 151));
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        BtnDelete.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        BtnDelete.setForeground(new java.awt.Color(58, 179, 151));
        BtnDelete.setText("Delete");
        BtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                                .addGap(309, 309, 309)
                                .addComponent(inputHargaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(143, 143, 143)
                                        .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(inputCari)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(inputNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(inputStokBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(inputKadaluarsa, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(inputTanggalMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))))))))
                        .addGap(84, 84, 84))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(414, 414, 414)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(492, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputHargaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputStokBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputTanggalMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputKadaluarsa, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputCari, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(534, 534, 534))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(44, 44, 44)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(1079, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNavDataBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNavDataBarangActionPerformed
        
    }//GEN-LAST:event_btnNavDataBarangActionPerformed

    private void btnNavDataPegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNavDataPegawaiActionPerformed
        dispose();
        DataPegawaiAdmin.main(null);
    }//GEN-LAST:event_btnNavDataPegawaiActionPerformed

    private void btnNavDataTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNavDataTransaksiActionPerformed
        dispose();
        FormDataTransaksi.main(null);
    }//GEN-LAST:event_btnNavDataTransaksiActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        dispose();
        Main.main(null);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void inputHargaBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputHargaBarangActionPerformed
        inputTanggalMasuk.requestFocus();
    }//GEN-LAST:event_inputHargaBarangActionPerformed

    private void inputNamaBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNamaBarangActionPerformed
        inputStokBarang.requestFocus();
    }//GEN-LAST:event_inputNamaBarangActionPerformed

    private void inputTanggalMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputTanggalMasukActionPerformed
        inputKadaluarsa.requestFocus();
    }//GEN-LAST:event_inputTanggalMasukActionPerformed

    private void inputStokBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputStokBarangActionPerformed
        inputHargaBarang.requestFocus();
    }//GEN-LAST:event_inputStokBarangActionPerformed

    private void inputKadaluarsaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputKadaluarsaActionPerformed
        
    }//GEN-LAST:event_inputKadaluarsaActionPerformed

    private void inputCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputCariActionPerformed
        btnCari.doClick();
    }//GEN-LAST:event_inputCariActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        try {
        String query = "INSERT INTO barang (nama_barang, harga, stok, tanggal_masuk, tanggal_kadaluarsa) VALUES (?, ?, ?, ?, ?)";
        PreparedStatement pstmt = mysqlconfig.prepareStatement(query);
        
        pstmt.setString(1, inputNamaBarang.getText());
        pstmt.setString(2, inputHargaBarang.getText());
        pstmt.setString(3, inputStokBarang.getText());
        pstmt.setString(4, inputTanggalMasuk.getText());
        pstmt.setString(5, inputKadaluarsa.getText());
        
        int rowsInserted = pstmt.executeUpdate();
        
        if (rowsInserted > 0) {
            JOptionPane.showMessageDialog(null, "Data Berhasil Ditambahkan");
            kosong();
            loadData();
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
    }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        int selectedRow = tabelBarang.getSelectedRow();
        if (selectedRow != -1) {
            String namaBarangBaru = inputNamaBarang.getText();
            String hargaBarangBaru = inputHargaBarang.getText();
            String stokBarangBaru = inputStokBarang.getText();
            String tanggalMasukBaru = inputTanggalMasuk.getText();
            String tanggalKadaluarsaBaru = inputKadaluarsa.getText();

            String kodeBarang = tabelBarang.getValueAt(selectedRow, tabelBarang.getColumn("KODE")
                    .getModelIndex()).toString();

            try {
                
                String sql = "UPDATE barang SET nama_barang = ?, harga = ?, stok = ?, tanggal_masuk = ?, "
                        + "tanggal_kadaluarsa = ? WHERE kode_barang = ?";
                PreparedStatement pstmt = mysqlconfig.prepareStatement(sql);
                pstmt.setString(1, namaBarangBaru);
                pstmt.setString(2, hargaBarangBaru);
                pstmt.setString(3, stokBarangBaru);
                pstmt.setString(4, tanggalMasukBaru);
                pstmt.setString(5, tanggalKadaluarsaBaru);
                pstmt.setString(6, kodeBarang);

                int updatedRows = pstmt.executeUpdate();
                if (updatedRows > 0) {
                    JOptionPane.showMessageDialog(this, "Data berhasil diupdate.", 
                            "Informasi", JOptionPane.INFORMATION_MESSAGE);
                    loadData();
                } else {
                    JOptionPane.showMessageDialog(this, "Gagal mengupdate data.", 
                            "Error", JOptionPane.ERROR_MESSAGE);
                }
                pstmt.close();
                
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), 
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Pilih baris tabel terlebih dahulu.", 
                    "Informasi", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_btnEditActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        String keyword = inputCari.getText();
        cariBarang(keyword);
    }//GEN-LAST:event_btnCariActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        dispose();
        DashboardAdmin.main(null);
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void BtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDeleteActionPerformed
        
        int selectedRow = tabelBarang.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Pilih baris yang ingin dihapus.", 
                    "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this, "Anda yakin ingin menghapus data ini?", 
                "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        String kodeBarang = tabelBarang.getValueAt(selectedRow, 0).toString();

        try {
            String sql = "DELETE FROM barang WHERE kode_barang = ?";
            PreparedStatement pstmt = mysqlconfig.prepareStatement(sql);
            pstmt.setString(1, kodeBarang);
            
            int deletedRows = pstmt.executeUpdate();
            if (deletedRows > 0) {
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus.", 
                        "Informasi", JOptionPane.INFORMATION_MESSAGE);
                loadData();
            } else {
                JOptionPane.showMessageDialog(this, "Gagal menghapus data.", 
                        "Error", JOptionPane.ERROR_MESSAGE);
            }

            pstmt.close();
//            mysqlconfig.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), 
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BtnDeleteActionPerformed

    private void tabelBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelBarangMouseClicked
        int row = tabelBarang.rowAtPoint(evt.getPoint());
        inputNamaBarang.setText(tabelBarang.getValueAt(row, 1).toString());
        inputHargaBarang.setText(tabelBarang.getValueAt(row, 2).toString());
        inputStokBarang.setText(tabelBarang.getValueAt(row, 3).toString());
        inputTanggalMasuk.setText(tabelBarang.getValueAt(row, 4).toString());
        inputKadaluarsa.setText(tabelBarang.getValueAt(row, 5).toString());

    }//GEN-LAST:event_tabelBarangMouseClicked

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        kosong();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnNavSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNavSupplierActionPerformed
        dispose();
        FormSupplierAdmin.main(null);
    }//GEN-LAST:event_btnNavSupplierActionPerformed

    private void btnNavTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNavTransaksiActionPerformed
        dispose();
        Transaksi.main(null);
    }//GEN-LAST:event_btnNavTransaksiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnDelete;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnNavDataBarang;
    private javax.swing.JButton btnNavDataPegawai;
    private javax.swing.JButton btnNavDataTransaksi;
    private javax.swing.JButton btnNavSupplier;
    private javax.swing.JButton btnNavTransaksi;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JPanel btnTransaksi;
    private javax.swing.JTextField inputCari;
    private javax.swing.JTextField inputHargaBarang;
    private javax.swing.JTextField inputKadaluarsa;
    private javax.swing.JTextField inputNamaBarang;
    private javax.swing.JTextField inputStokBarang;
    private javax.swing.JTextField inputTanggalMasuk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelBarang;
    // End of variables declaration//GEN-END:variables
}
